#!/bin/bash

FILE='.git/COMMIT_EDITMSG'
MESSAGE=$(cat "$FILE")

get_ticket () {
    TICKET=$(grep -o "[A-Z]\{2,7\}-[0-9]\+" <<< "$1")
}

get_ticket "$MESSAGE"

if [ -z "$TICKET" ] ; then
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    get_ticket "$BRANCH"

    if [ -z "$TICKET" ]; then
        echo "No ticket number (ex: CORE-123) found in commit message or branch."
        exit 0
    fi

    TYPE=$(echo "$MESSAGE" | grep -oE "^[a-z]+")
    
    REST=$(echo "$MESSAGE" | sed -E "s/^[a-z]+: //")

    if [ -n "$TYPE" ] && [ -n "$REST" ]; then
        echo "${TYPE}(${TICKET}): ${REST}" > "$FILE"
    else
        echo "Commit message is non-conventional."
        exit 0
    fi
fi