name: Branch Stage Workflow

on:
  push:
    branches:
      - stage

jobs:
  check-freeze-commit:
    runs-on: ubuntu-latest
    outputs:
      has-freeze: ${{ steps.check-commit.outputs.has-freeze }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for freeze in commit message
        id: check-commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"

          if echo "$COMMIT_MESSAGE" | grep -qi "freeze"; then
            echo "has-freeze=true" >> $GITHUB_OUTPUT
            echo "Found 'freeze' in commit message, will create new version"
          else
            echo "has-freeze=false" >> $GITHUB_OUTPUT
            echo "No 'freeze' found in commit message"
          fi

  jira-version-manager:
    needs: check-freeze-commit
    uses: ./.github/workflows/manager-jira-version.yml
    with:
      branch_name: stage
      force_new_version: ${{ needs.check-freeze-commit.outputs.has-freeze == 'true' }}
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

  jira-issues-manager:
    needs: jira-version-manager
    uses: ./.github/workflows/manager-jira-issues.yml
    with:
      new_version: ${{ needs.jira-version-manager.outputs.NEW_VERSION }}
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

  package-version-manager:
    needs: jira-version-manager
    uses: ./.github/workflows/manager-package-version.yml
    with:
      new_version: ${{ needs.jira-version-manager.outputs.NEW_VERSION }}
    secrets:
      WORKFLOW: ${{ secrets.WORKFLOW }}

  back-merge-manager:
    needs:
      [
        jira-version-manager,
        jira-issues-manager,
        package-version-manager,
        check-freeze-commit,
      ]
    if: needs.check-freeze-commit.outputs.has-freeze == 'false'
    uses: ./.github/workflows/manager-back-merge.yml
    with:
      back_merge_targets: "dev"
    secrets:
      WORKFLOW: ${{ secrets.WORKFLOW }}
