name: Branch Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  jira-version-manager:
    uses: ./.github/workflows/manager-jira-version.yml
    with:
      branch_name: dev
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

  jira-issues-manager:
    needs: jira-version-manager
    uses: ./.github/workflows/manager-jira-issues.yml
    with:
      new_version: ${{ needs.jira-version-manager.outputs.NEW_VERSION }}
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

  debug-version-transfer:
    needs: jira-version-manager
    runs-on: ubuntu-latest
    steps:
      - name: Debug version transfer
        run: |
          echo "Debug: Checking version transfer"
          echo "NEW_VERSION from jira-version-manager: '${{ needs.jira-version-manager.outputs.NEW_VERSION }}'"
          echo "VERSION_WITHOUT_PREFIX from jira-version-manager: '${{ needs.jira-version-manager.outputs.VERSION_WITHOUT_PREFIX }}'"
          echo "All outputs from jira-version-manager:"
          echo "${{ toJSON(needs.jira-version-manager.outputs) }}"

  package-version-manager:
    needs: jira-version-manager
    uses: ./.github/workflows/manager-package-version.yml
    with:
      new_version: ${{ needs.jira-version-manager.outputs.NEW_VERSION }}
    secrets:
      WORKFLOW: ${{ secrets.WORKFLOW }}
