name: Branch Stage Workflow

on:
  push:
    branches:
      - stage

jobs:
  jira-version-manager:
    uses: ./.github/workflows/manager-jira-version.yml
    with:
      branch_name: stage
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

  jira-issues-manager:
    needs: jira-version-manager
    uses: ./.github/workflows/manager-jira-issues.yml
    with:
      new_version: ${{ needs.jira-version-manager.outputs.NEW_VERSION }}
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

  package-version-manager:
    needs: jira-version-manager
    uses: ./.github/workflows/manager-package-version.yml
    with:
      new_version: ${{ needs.jira-version-manager.outputs.NEW_VERSION }}
    secrets:
      WORKFLOW: ${{ secrets.WORKFLOW }}

  back-merge-manager:
    needs: [jira-version-manager, jira-issues-manager, package-version-manager]
    uses: ./.github/workflows/manager-back-merge.yml
    with:
      back_merge_targets: "dev"
    secrets:
      WORKFLOW: ${{ secrets.WORKFLOW }}
