name: Jira Release Manager

on:
  push:
    branches:
      - dev
      - release
      - master

jobs:
  manage-jira-release:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: https://iamdima.atlassian.net
      JIRA_PROJECT_KEY: IT
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW }}

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Get Project ID
        run: |
          PROJECT_INFO=$(curl -s -u $JIRA_EMAIL:$JIRA_TOKEN -X GET "$JIRA_BASE_URL/rest/api/3/project/$JIRA_PROJECT_KEY")
          PROJECT_ID=$(echo "$PROJECT_INFO" | jq -r '.id')
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Find or Use Existing Version
        run: |
          RESPONSE=$(curl -s -u $JIRA_EMAIL:$JIRA_TOKEN -X GET "$JIRA_BASE_URL/rest/api/3/project/$JIRA_PROJECT_KEY/versions")
          if [[ "$BRANCH_NAME" == "dev" ]]; then
            LAST_VERSION=$(echo "$RESPONSE" | jq -r '.[] | select(.released == false) | select(.name | startswith("IT")) | .name' | sort -V | tail -n1)
          else
            LAST_VERSION=$(echo "$RESPONSE" | jq -r '.[] | select(.released == false) | select(.name | startswith("IT")) | .name' | sort -V | head -n1)
          fi

          if [ -z "$LAST_VERSION" ]; then
            LAST_RELEASED_VERSION=$(echo "$RESPONSE" | jq -r '.[] | select(.released == true) | select(.name | startswith("IT")) | .name' | sort -V | tail -n1)
            if [ -z "$LAST_RELEASED_VERSION" ]; then
              PREFIX="IT"; MAJOR=1; MINOR=0; PATCH=0
            else
              PREFIX=${LAST_RELEASED_VERSION%%[0-9]*}
              VERSION_NUM=${LAST_RELEASED_VERSION#$PREFIX}
              MAJOR=$(echo $VERSION_NUM | cut -d. -f1)
              MINOR=$(echo $VERSION_NUM | cut -d. -f2)
              PATCH=$(echo $VERSION_NUM | cut -d. -f3)
              MINOR=$((MINOR + 1)); PATCH=0
            fi
          else
            PREFIX=${LAST_VERSION%%[0-9]*}
            VERSION_NUM=${LAST_VERSION#$PREFIX}
            MAJOR=$(echo $VERSION_NUM | cut -d. -f1)
            MINOR=$(echo $VERSION_NUM | cut -d. -f2)
            PATCH=$(echo $VERSION_NUM | cut -d. -f3)
            if [[ "$BRANCH_NAME" == "master" ]]; then
              PATCH=$((PATCH + 1))
            fi
          fi

          NEW_VERSION="${PREFIX}${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          VERSION_EXISTS=$(echo "$RESPONSE" | jq -r --arg NAME "$NEW_VERSION" '.[] | select(.name == $NAME) | .id')
          if [ -z "$VERSION_EXISTS" ]; then
            curl -s -u $JIRA_EMAIL:$JIRA_TOKEN \
              -X POST "$JIRA_BASE_URL/rest/api/3/version" \
              -H "Content-Type: application/json" \
              -d "{
                \"description\": \"Auto-created release\",
                \"name\": \"$NEW_VERSION\",
                \"projectId\": $PROJECT_ID,
                \"released\": false
              }"
          fi

      - name: Update Jira Issues and Move to RFQA
        if: (github.ref_name == 'dev' || github.ref_name == 'release') && !contains(github.event.head_commit.message, 'Merge pull request')
        run: |
          COMMITS=$(git log -1 --pretty=%B)
          ISSUE_KEYS=$(echo "$COMMITS" | grep -Eo "$JIRA_PROJECT_KEY-[0-9]+" | uniq)
          for issue in $ISSUE_KEYS; do
            curl -s -u $JIRA_EMAIL:$JIRA_TOKEN \
              -X PUT "$JIRA_BASE_URL/rest/api/3/issue/$issue" \
              -H "Content-Type: application/json" \
              -d "{
                \"update\": {
                  \"fixVersions\": [
                    {
                      \"add\": {\"name\": \"$NEW_VERSION\"}
                    }
                  ]
                }
              }"
            TRANSITION_ID=$(curl -s -u $JIRA_EMAIL:$JIRA_TOKEN -X GET "$JIRA_BASE_URL/rest/api/3/issue/$issue/transitions" | jq -r '.transitions[] | select(.name=="RFQA") | .id')
            if [ -n "$TRANSITION_ID" ]; then
              curl -s -u $JIRA_EMAIL:$JIRA_TOKEN \
                -X POST "$JIRA_BASE_URL/rest/api/3/issue/$issue/transitions" \
                -H "Content-Type: application/json" \
                -d "{\"transition\": {\"id\": \"$TRANSITION_ID\"}}"
            fi
          done

      - name: Update package.json and package-lock.json version if needed
        run: |
          VERSION_WITHOUT_PREFIX=${NEW_VERSION#"IT"}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" = "$VERSION_WITHOUT_PREFIX" ]; then
            echo "SKIP_VERSION_UPDATE=true" >> $GITHUB_ENV
          else
            npm version --no-git-tag-version "$VERSION_WITHOUT_PREFIX"
            echo "SKIP_VERSION_UPDATE=false" >> $GITHUB_ENV
          fi

      - name: Commit updated package files if version changed
        if: env.SKIP_VERSION_UPDATE == 'false'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package.json package-lock.json
          git commit -m "🔖 Update package version to $NEW_VERSION"

      - name: Push changes if version changed
        if: env.SKIP_VERSION_UPDATE == 'false'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.WORKFLOW }}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}

      - name: Release version in Jira (only on master)
        if: github.ref_name == 'master'
        run: |
          VERSIONS=$(curl -s -u $JIRA_EMAIL:$JIRA_TOKEN -X GET "$JIRA_BASE_URL/rest/api/3/project/$JIRA_PROJECT_KEY/versions")
          VERSION_TO_RELEASE=$(echo "$VERSIONS" | jq -r '.[] | select(.released == false) | select(.name | startswith("IT")) | .name' | sort -V | head -n1)
          if [ -n "$VERSION_TO_RELEASE" ]; then
            VERSION_ID=$(echo "$VERSIONS" | jq -r --arg NAME "$VERSION_TO_RELEASE" '.[] | select(.name == $NAME) | .id')
            TODAY=$(date +%Y-%m-%d)
            curl -s -u $JIRA_EMAIL:$JIRA_TOKEN \
              -X PUT "$JIRA_BASE_URL/rest/api/3/version/$VERSION_ID" \
              -H "Content-Type: application/json" \
              -d "{\"released\": true, \"releaseDate\": \"$TODAY\"}"
          fi

      - name: Create GitHub Tag and Release (only on master)
        if: github.ref_name == 'master' && env.SKIP_VERSION_UPDATE == 'false'
        run: |
          TAG_NAME="v${NEW_VERSION}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        if: github.ref_name == 'master' && env.SKIP_VERSION_UPDATE == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release v${{ env.NEW_VERSION }}
          body: |
            Automated release based on Jira version ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform back-merge
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.WORKFLOW }}@github.com/${{ github.repository }}
          git fetch --all
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            git merge master release --no-ff --no-commit || { git merge --abort; exit 1; }
            git commit -m "🔄 Back-merge master into release"
            git push origin release

            git merge master dev --no-ff --no-commit || { git merge --abort; exit 1; }
            git commit -m "🔄 Back-merge master into dev"
            git push origin dev
          elif [[ "${{ github.ref_name }}" == "release" ]]; then
            git merge release dev --no-ff --no-commit || { git merge --abort; exit 1; }
            git commit -m "🔄 Back-merge release into dev"
            git push origin dev
          fi
