name: Jira Issues Manager

on:
  workflow_call:
    inputs:
      new_version:
        required: true
        type: string
      branch_name:
        required: false
        type: string
        default: ""
    secrets:
      JIRA_EMAIL:
        required: true
      JIRA_TOKEN:
        required: true

jobs:
  manage-jira-issues:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: https://iamdima.atlassian.net
      JIRA_PROJECT_KEY: IT
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Update Jira Issues and Move to RFQA
        env:
          NEW_VERSION: ${{ inputs.new_version }}
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          echo "Updating issues FixVersion and moving to appropriate status..."
          echo "Input new_version: '${{ inputs.new_version }}'"
          echo "Branch name: '${{ inputs.branch_name }}'"
          COMMITS=$(git log -1 --pretty=%B)
          echo "Commits: $COMMITS"

          ISSUE_KEYS=$(echo "$COMMITS" | grep -Eo "$JIRA_PROJECT_KEY-[0-9]+" | uniq)

          for issue in $ISSUE_KEYS; do
            echo "Processing issue $issue"
            echo "Setting version '$NEW_VERSION' for issue $issue"

            curl -s -u $JIRA_EMAIL:$JIRA_TOKEN \
              -X PUT "$JIRA_BASE_URL/rest/api/3/issue/$issue" \
              -H "Content-Type: application/json" \
              -d "{
                \"update\": {
                  \"fixVersions\": [
                    {
                      \"add\": {\"name\": \"$NEW_VERSION\"}
                    }
                  ]
                }
              }"

            TRANSITIONS=$(curl -s -u $JIRA_EMAIL:$JIRA_TOKEN \
              -X GET "$JIRA_BASE_URL/rest/api/3/issue/$issue/transitions" \
              -H "Accept: application/json")

            # Determine target status based on branch
            if [[ "$BRANCH_NAME" == "main" ]]; then
              echo "Main branch detected, moving to Done"
              TARGET_STATUS="Done"
            else
              echo "Non-main branch, moving to RFQA"
              TARGET_STATUS="RFQA"
            fi

            TRANSITION_ID=$(echo "$TRANSITIONS" | jq -r --arg STATUS "$TARGET_STATUS" '.transitions[] | select(.name==$STATUS) | .id')

            if [ -n "$TRANSITION_ID" ]; then
              echo "Moving issue $issue to $TARGET_STATUS with transition ID $TRANSITION_ID"

              curl -s -u $JIRA_EMAIL:$JIRA_TOKEN \
                -X POST "$JIRA_BASE_URL/rest/api/3/issue/$issue/transitions" \
                -H "Content-Type: application/json" \
                -d "{
                  \"transition\": {
                    \"id\": \"$TRANSITION_ID\"
                  }
                }"
            else
              echo "Transition to $TARGET_STATUS not found for issue $issue, skipping."
            fi
          done
